openapi: "3.0.0"
info:
  version: 1.0.0
  title: "currency converter"
servers:
  - url: http://127.0.0.1:8080/api
    description: Local
paths:
  /currency/rates:
    get:
      summary: Get currency rates
      operationId: currency-rates
      tags: [ "currency" ]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './schemas/CurrencyRates.yaml'
        '500':
          $ref: '#/components/responses/500ServerError'
  /currency/convert:
    post:
        summary: Convert currency
        operationId: currency-convert
        tags: [ "currency" ]
        requestBody:
            description: Request body
            required: true
            content:
              application/json:
                schema:
                  $ref: './schemas/CurrencyConvertRequest.yaml'
        responses:
            '200':
              description: Successful operation
              content:
                application/json:
                  schema:
                    $ref: './schemas/CurrencyConvertResponse.yaml'
            '500':
              $ref: '#/components/responses/500ServerError'
  /tech/health:
    get:
      summary: Get service health status
      operationId: tech-health
      security: []
      tags: [ "tech" ]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './schemas/HealthStatus.yaml'
        '500':
          $ref: '#/components/responses/500ServerError'
  /tech/guarded-health:
    get:
      summary: Get auth-guarded demo endpoint
      operationId: tech-guarded-health
      tags: [ "tech" ]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: './schemas/HealthStatus.yaml'
        '401':
          $ref: '#/components/responses/401NeedAuthError'
        '500':
          $ref: '#/components/responses/500ServerError'
components:
  schemas:
    ServerError:
      $ref: "./schemas/ServerError.yaml"
  responses:
    401NeedAuthError:
      description: Authentication header is not provided or incorrect
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/ServerError'
              - properties:
                  status:
                    example: error
                  code:
                    example: 401
                  message:
                    example: "Authentication Required"
    500ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerError'
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: bearer
      description: All requests should contain Authorization header with Bearer format, example of token "XCDQ5ERT3NFST2IF"
security:
  - ApiKeyAuth: []
